### ISSUE TITLE
Falha no Google docs

### ISSUE THREAD

**Issue by djedu28** [FilipePS/Traduzir-paginas-web#104]
Muito bom a nova versão, obrigado por add o yandex.

Filipe, depois verifica a falha no CSS que ocorre ao traduzir um google docs, 

com a nova versão ele acabou traduzindo automaticamente meu texto e reparei que falhou o CSS do documento na pagina de edição de documento do google (eu desativei no site, já que não usava a tradução no google docs, mas fica a dica pra próxima atualização, alguém pode precisar usar).

- - - - - - - - - - -- - - - - - - - - - - - -- - - - - - - - - - -
avaliação antiga :
https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/reviews/1647596/
- - - - - - - - - - -- - - - - - - - - - - - -- - - - - - - - - - -

❤️  Obrigado por melhorar meus dias e produtividade 😄

**Comment by FilipePS** [comment]
Eu testei em um documento e não vi problema nenhum.

**Comment by Vingolf** [comment]
I want to emphasize that the addon of @FilipePS is very helpful and it improves with every update.👍

When I became aware of this issue (# 104), I had to translate the text, 
since I do not understand portuguese. I did this with your addon for sure. 😃

> avaliação antiga :
> https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web/reviews/1647596/

Following this link to addons.mozilla.org the addon does not work anymore. 
I am aware that this is a restriction of the firefox api.

My solution to translate the text was to copy the text from addons.mozilla.org
 and paste it into a window on deepl.com.

I wonder if the restrictions for addons allow translating a text in a popup window or in the sidebar? 🤔

**Comment by FilipePS** [comment]
@djedu28 Does this issue still occur? could you give more details?


@Vingolf
> I wonder if the restrictions for addons allow translating a text in a popup window or in the sidebar? 🤔

This has already been implemented. When selecting text, translate using the button in the context menu.

**Comment by FilipePS** [comment]
I'm closing this issue. If you have any more problems, please create a new issue.
