### ISSUE TITLE
Alt T doesn't work on firefox

### ISSUE THREAD

**Issue by magicisreals1234** [FilipePS/Traduzir-paginas-web#145]
On firefox, Alt-T opens the tools bar. Having an alternative, or keymappable option would be nice.

**Comment by FilipePS** [comment]
The Firefox shortcut to open the toolbar is not Alt + T
You are probably using an extension that is doing this.

To manage the extension shortcut keys, follow these steps:

- Open the Firefox extension manager `about:addons`
- Click on the gears icon
- Select "Manage extension shortcuts"

**Comment by magicisreals1234** [comment]
Oh I made a stupid mistake, I mean alt opens this bar thing, https://i.imgur.com/us1uSTj.png, and then T opens the tools section of it.

Thanks for the help, though! The extension thing worked.

**Comment by FilipePS** [comment]
In this case it is not an extension interfering. Apparently in some specific languages like Simplified Chinese. Firefox uses Alt + T as a shortcut to open that.

In the next version I will add an easier way to change the shortcut keys.

I'm still not sure if I should change Alt + T to another as a default, since this problem does not affect everyone, and some are already used to Alt + T

**Comment by FilipePS** [comment]
In [Version 9.0](https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.0) the shortcut was changed to `Ctrl+Alt+T`. And you have options to change it in the settings.
