### ISSUE TITLE
快捷键 Alt+T 失效

### ISSUE THREAD

**Issue by crazy3min** [FilipePS/Traduzir-paginas-web#146]
浏览器：firefox 88.0 (64 位)

浏览器设置：永久启用隐私浏览模式；不显示菜单栏

现象：第一次打开浏览器，快捷键 Alt+T，会直接弹出菜单栏，无法进行翻译网页。

但是如果这时候设置显示菜单栏后， Alt+T 正常翻译，再设置隐藏菜单栏，Alt+T 也正常翻译。

关闭浏览器后重新打开，将重复上面的现象。

![图片](https://user-images.githubusercontent.com/45255042/116374853-45a95d00-a841-11eb-9c89-63f0d2388cd6.png)

问题：这个是浏览器的问题，还是插件的问题？

**Comment by FilipePS** [comment]
Apparently in some specific languages like Simplified Chinese. Firefox uses Alt + T as a shortcut to open that.

In the next version I will add an easier way to change the shortcut keys.

I'm still not sure if I should change Alt + T to another as a default, since this problem does not affect everyone, and some are already used to Alt + T

**Comment by FilipePS** [comment]
And as there is already an issue about this problem, I am closing this one. #145
