### ISSUE TITLE
Do not work some hotkeys in version 9.0

### ISSUE THREAD

**Issue by oleg-sgh** [FilipePS/Traduzir-paginas-web#153]
Do not work hotkeys that start with "Ctrl":
Ctrl + Alt + T
Ctrl + Alt + S
Ctrl + Alt + Q

Windows 7x64. Firefox 88.0.1

**Comment by FilipePS** [comment]
In version 9.0 I used shortcut keys like` Ctrl+Alt+T` instead of `Alt+T` as before, because in some languages Firefox uses `Alt + some letter` for some things.
I have no intention of changing the standard keys again.

Testing this bug, I realized that when using the Russian layout, you can't change the shortcut keys either (at least not due to my extension settings). I'll fix this.
