### ISSUE TITLE
[Feature request] 4th target language

### ISSUE THREAD

**Issue by ghost** [FilipePS/Traduzir-paginas-web#154]
Is there a possibility of implementing a 4th target language within the addon? I think I’m not the only one who would find this feature useful :)

**Comment by copergopher934** [comment]
Yes, and your addon has been a godsend since it’s faster, better organized and more convenient than any other on the mozilla store, and I really want to keep using it. I wish there was at least a way to somehow set English as a primary, so that different languages get translated to it, but still retain the 3 other languages in the pop-up (instead of 2 + English as is the case atm). I understand that I’m grasping at straws here, but idk if that might be a simpler problem to solve, or something you would try to look into.

Anyhow, thank you for the quick response, and all the work you did on this project.

**Comment by FilipePS** [comment]
This feature was implemented in the previous version.
