### ISSUE TITLE
Feature Request: Android Version

### ISSUE THREAD

**Issue by kodi-rc** [FilipePS/Traduzir-paginas-web#193]
Could you create an android mobile version for this extension?

**Comment by FilipePS** [comment]
The extension has Firefox support, the problem is that Firefox has made it difficult to install other extensions than those listed in the extension manager.
Install Firefox Nightly and see this tutorial.
https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/
