### ISSUE TITLE
New permissions required - why?

### ISSUE THREAD

**Issue by jamy015** [FilipePS/Traduzir-paginas-web#207]
Hi,

First of all, thanks for the great add-on. I've been using it for a while now.

I got a message in my Firefox menu that the add-on needs new permissions:
![image](https://user-images.githubusercontent.com/3188721/124369380-af901980-dc6b-11eb-9fae-aca4fbba2003.png)

Why is this new permission needed?

**Comment by FilipePS** [comment]
Because of the new feature `Automatically translate when clicking on a link that takes you to the same domain as the current site`

**Comment by jamy015** [comment]
Ok, thanks for explaining!

**Comment by FilipePS** [comment]
Just to give you more details.
This permission was requested because the extension is using the [webNavigation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation) api. This api is being used in the extension to know if the user clicked on a link and which site opened through that click.
This information is needed to implement that new feature.

**Comment by FilipePS** [comment]
As of version 9.2 this permission is optional.
So it will only be required if you enable the `Automatically translate when clicking on a link that takes you to the same domain as the current site` option.
