### ISSUE TITLE
[Mobile] twice in addons preview

### ISSUE THREAD

**Issue by B0pol** [FilipePS/Traduzir-paginas-web#33]
(Using iceweasel https://github.com/interfect/fenix)

Why is it twice in addons? Is it a bug or intentional? It is disturbing and think you should be there only once 

<img src="https://i.ibb.co/H76c89G/Screenshot-20200903-110442-Iceweasel.png" width="300">

**Comment by FilipePS** [comment]
It's not exactly a bug, but I'll fix it.
If you want to know details:
Before, the extension just had an icon in the address bar (pageAction), which did not appear for Firefox Mobile because it would be strange to see an icon to translate all the time.
Recently resolving to change the translate button for the toolbar (browserAction), which was very good for Firefox Mobile, has generated several complaints for those who use Firefox Desktop. So decide to leave them both, and whoever didn't want 1 of them just had to hide it manually.
Now in this Firefox Fenix, the menu is showing both pageAction and browserAction.
The browserAction cannot be hidden, whether it exists or not. the pageAction can be hidden.

Now that pageAction appears in the Firefox Fenix Menu, I'm going to remove browserAction.

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/355ef23a7bbc24fe3b04513f6e989c44f796a9dd
