### ISSUE TITLE
Automatically Translate Option Not Working

### ISSUE THREAD

**Issue by MadZiontist** [FilipePS/Traduzir-paginas-web#352]
I select the automatically translate option for many sites in various languages, but when I revisit them the text is never automatically translated, and is always in the same native language it was originally in. I have to keep manually translating pages. I don't know that the option has worked on any page or language I've ever enabled it for.

**Comment by Necronasti** [comment]
Have you fixed this? It's really annoying.

**Comment by FilipePS** [comment]
If you used the `Always translate from` option and the site translation does not start automatically, the most likely reasons are:
1. The extension detected the site's language erroneously.
2. The website language is the same as your current target language.

**Comment by DeaD3R** [comment]
Same problem. I go to a Chinese website, hit always translate this website, refresh and it's in Chinese again. I think the problem is that the extension doesn't recognize the language, as it says (Unknown) **Original**. This is the website: https://cafe.daum.net/pot-tool/AZMV

I'd get not automatically translating if you have checked "Always translate from Chinese", since it can't recognize the language, but I think it should still work with "Always translate this page" regardless of if it recognizes the source language or not.
