### ISSUE TITLE
Which version is this?

### ISSUE THREAD

**Issue by Maneeha1234SL** [FilipePS/Traduzir-paginas-web#363]
I have received the latest version of the extension![image](https://user-images.githubusercontent.com/83775004/152122298-ebdd7bb3-1352-4c9f-9620-7f26eb444734.png)

**Comment by FilipePS** [comment]
I receive an email with a preview of each issue/pull request in this repository. So I know what you posted.
This is a development version. This transparent interface will only be available in chromium based browsers, due to a firefox configuration.
I would like to know if this issue is just a doubt, or if you have some criticisms of this interface.
