### ISSUE TITLE
"Translate selected text" cannot be hidden in context menu.

### ISSUE THREAD

**Issue by ghcsd** [FilipePS/Traduzir-paginas-web#42]
![image](https://user-images.githubusercontent.com/32384764/92699204-df3e0000-f37f-11ea-834a-fb33512edb02.png)
I have set `Show the option to translate the page in the context menu` to `No`.

**Comment by Jacosci** [comment]
+1 I have encountered this too

**Comment by FilipePS** [comment]
In this case, this button is to translate the selected text and not the page.

**Comment by Jacosci** [comment]
I have both options set to no as you can see from my screenshot below. But the context menu is still there.
Granted I haven't tested it on different machine or clean profile. So I can't certainly say if the problem is only on my end.
Hopefully someone can test it if I'm unable to do it in the next few days.
![image](https://user-images.githubusercontent.com/10607576/92779446-4386b100-f3cc-11ea-8e96-19d0624bce9a.png)

**Comment by Ayesh** [comment]
With configuration as same as @Jacosci, I can confirm that this exists in my version as well. 
Firefox 81 beta, Windows 10 64 bit. Addn version 7.3.4.

![image](https://user-images.githubusercontent.com/811553/92991917-0b3cbb00-f511-11ea-9ff8-9ce4eba3f426.png)


Further, it appears to create a small div in root HTML, presumably for the pop-in button to selected text translation. Web pages like https://ayeshious.com with root level div changed in CSS shows this up.

![image](https://user-images.githubusercontent.com/811553/92991935-23acd580-f511-11ea-92e1-fb492103759e.png)

**Comment by FilipePS** [comment]
https://github.com/FilipePS/Traduzir-paginas-web/commit/53d99f4c865ce9d2fa49abd963855a97d436faad
