### ISSUE TITLE
This translation is heavily truncated and does not contain the entire content of the post.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [FilipePS/Traduzir-paginas-web#449]
@FilipePS See this issue on Twitter:

This post:
https://twitter.com/gamingonlinux/status/1554433336600412161

Original:
![obraz](https://user-images.githubusercontent.com/16800535/182675480-85fc1674-b12a-4319-94aa-e66c910e4142.png)

Translation:
![obraz](https://user-images.githubusercontent.com/16800535/182675526-524ea302-7852-47ca-a157-8edda8f1ddcd.png)

This translation is heavily truncated and does not contain the entire content of the post.

_Originally posted by @lukaszpolowczyk in https://github.com/FilipePS/Traduzir-paginas-web/issues/394#issuecomment-1204289663_

**Comment by FilipePS** [comment]
A simple way to fix this is to remove the html tag `<a>` from the `htmlTagsInlineText` array in the `pageTranslator.js` file.
The problem with doing this is that it will reduce the quality of translation on other sites that the html tag `<a>` inserted in the middle of sentences.
If you want to look for another solution...

**Comment by lukaszpolowczyk** [comment]
@FilipePS It's not just about `<a>`, here is a full translation of the text itself:
![obraz](https://user-images.githubusercontent.com/16800535/184013141-a06b130e-64d6-4c06-bdf6-89d3d111218f.png)

https://translate.google.pl/?sl=auto&tl=pl&text=Linux%20user%20share%20on%20Steam%20continues%20rising%20%E2%80%94%20highest%20for%20years%20again%20(thanks%20Steam%20Deck)&op=translate

Missing is "Udział użytkowników Linuksa na Steamie " at the beginning of the text.
And there is also a slightly different translation, with the cut off "nadal rośnie" and with the full "stale rośnie".

The extension translates as if the beginning was cut out. Here the translation considering that part is cut:
![obraz](https://user-images.githubusercontent.com/16800535/184014992-03f20e73-28e3-4fa2-a247-34b3dde4b6ac.png)
https://translate.google.pl/?sl=auto&tl=en&text=continues%20rising%20%E2%80%94%20highest%20for%20years%20again%20(thanks%20Steam%20Deck)&op=translate

Now it is almost identical.

The log shows that the source is whole, and somewhere along the way it is truncated and this truncation is translated.
Or is it a different version of Google Translator that truncates like this? What is the reason for this?
![obraz](https://user-images.githubusercontent.com/16800535/184016763-78180797-0b8b-48d0-9370-51386a5255ea.png)


---

The problem is not only with `<a>`.

**Comment by FilipePS** [comment]
When translating using chrome's native translator, the same problem occurs on this twitch.
Google translator usually changes the order of the text to increase the translation quality, which usually causes some html tags to receive much more text than others.
Depending on the layout of the site, some tags cannot receive texts much larger than the original, if they do, it may break the site's layout and part of the text (or the entire text) may disappear.
So I removed the html tag `<a>` from the `htmlTagsInlineText` list and everything worked just fine as it should. (yes that works).
As it happened in the chrome translator and that change fixed the problem, I thought the real problem was the site layout.

After your answer I decided to do a deeper analysis and really the text is disappearing somewhere in the translation.

I isolated the testing area, basically extract the html from that twitch.
```HTML
<div>
    <span>Linux user share on Steam continues rising — highest for years again (thanks Steam Deck)</span>
    <a><span>https://</span>gamingonlinux.com/2022/08/linux-<span>user-share-on-steam-continues-rising-m-highest-for-years-again/</span><span>…</span></a>
</div>
```

I added a log point in the `_sourceArray3d` variable and `resultArray3d` in the `translationService.google.translateHTML` function.
And I got the following result:
```JSON
[
  [
    "Linux user share on Steam continues rising — highest for years again (thanks Steam Deck)",
    "https://",
    " gamingonlinux.com/2022/08/linux- ",
    "user-share-on-steam-continues-rising-m-highest-for-years-again/",
    "…"
  ]
]
```

It is clearly missing parts of the translation.

So I added log point to this variable `thisTranslationProgress`.
And I got the following result:
```JSON
[
  {
    "source": "<pre><a i=0>Linux user share on Steam continues rising — highest for years again (thanks Steam Deck)</a><a i=1>https://</a><a i=2> gamingonlinux.com/2022/08/linux- </a><a i=3>user-share-on-steam-continues-rising-m-highest-for-years-again/</a><a i=4>…</a></pre>",
    "translated": "<pre>A participação de usuários do Linux no Steam continua <a i=3>aumentando</a> <a i=0>- mais alta em anos novamente (obrigado Steam Deck</a> <a i=2>)</a> <a i=1>https://gameonlinux.com/2022/08/linux-user-share-on-steam-continues-rising-m-highest-for-years</a> <a i=3>-de novo/</a> <a i=4>…</a></pre>",
    "status": "complete"
  }
]
```

As you can see all the text was translated correctly and it was obvious to me what the problem was.
The code was written thinking that google translator would always return results around `<a i=INDEX>`.
And that's how it is most of the time, but this was not the case.
The part of the translation that disappeared was precisely the text that was not inside `<a i=INDEX>`.

If you want to fix this problem, feel free. If not, I'll fix it myself before releasing the next version.

**Comment by FilipePS** [comment]
I finally fixed this problem, part of the translation is no longer lost.
But visually in this twich nothing has changed. This is because the translated text (which is now no longer lost) is placed in tags that ended up being hidden.
And to solve this would have to do something specific to that site in pageTranslator.

**Comment by lukaszpolowczyk** [comment]
@FilipePS Complicated. Can you do it?

**Comment by FilipePS** [comment]
I will add an option for the person to specify the language of the site.
The translation is better and you won't have that problem.

**Comment by FilipePS** [comment]
Apparently this issue is no longer happening on that twitch.

**Comment by lukaszpolowczyk** [comment]
@FilipePS It is as it was:
![obraz](https://user-images.githubusercontent.com/16800535/202932174-724da5d7-28a6-4b1f-8d79-d3844f1eaf05.png)

Nothing is fixed.

Well, unless I am doing something wrong? Do I need to check an option? Will you describe it for me?

**Comment by FilipePS** [comment]
Everything works fine translates to Portuguese.

**Comment by FilipePS** [comment]
I remember that if the original language was specified this twitch was translated correctly, well apparently that's not true anymore, at least not when translating with Google.

One thing that works is disabling link text translation. Do you think the link text should be translated?

This problem is directly related to this other one: https://github.com/FilipePS/Traduzir-paginas-web/issues/647
The only difference is the target language and the `Do not sort translation results` option being active or not.

I have the solution in mind, soon I will implement it.
