### ISSUE TITLE
Auto Translate not working + other issues

### ISSUE THREAD

**Issue by DemonSwayer** [FilipePS/Traduzir-paginas-web#465]
**1. On PC (using Firefox 103.0.2):** The checkbox "Always translate from *language*" does not work for me for any language. Even if checked, it does not translate automatically when I open a new website in another language. I have to click the "Translate" Button manually.

**2. On Android (using Firefox Nightly 105.0a1):** Switching the option "Automatically translate when clicking on a link that takes you to the same domain as the current site" in the settings from "No" to "Yes" does not work because when you tap "Yes" nothing happens and it stays on "No". It works fine on PC, so it must be a bug on the Android version.

**3. On Android:** When you tap the 3 points on the popup, the menu opens. But when you tap the 3 points again, nothing happens. In order to close the menu you have to tap somewhere on the screen or you have to tap the "X" and then reload the page to make the popup appear again.

**4. On Android:** It would be nice if the color of the "Original" text on the pop would change to white/black (dependes on theme) when tapping "Translated" so it is clear that the translation has been activated. Right now when you tap "Translated" the "Original" text still stays highlighted. It is a bit confusing.

**Comment by FilipePS** [comment]
1. If you open a site in German, and you check the `Always translate from German` option and then click on translate. Every time you open a website in German it will be automatically translated.
This just won't happen based on these factors:
     1. The extension cannot detect the site's language.
      2. The extension detects that the site is in a language other than German (this can happen).
     3. If your target language is German.
        - That is, if the extension detects that the site's language is your current target language, the site is not automatically translated.

2. This option needs an additional permission, and because of a bug in Firefox Android, there is no way to request this permission.

3. This is something I need to look into.

4. This has already been fixed. The fix will be in the next version.
