### ISSUE TITLE
Error: Promised response from onMessage listener went out of scope

### ISSUE THREAD

**Issue by kesc11** [FilipePS/Traduzir-paginas-web#478]
This error will occur when I open any webpage of Firefox, even if I click nothing 

![屏幕截图 2022-09-16 184331](https://user-images.githubusercontent.com/51351113/190622249-c2533e00-1ce9-4afe-9111-0d00ce72b9cf.png)

 I open debugging in settings 

![屏幕截图 2022-09-16 184408](https://user-images.githubusercontent.com/51351113/190622258-bfb62f69-cbc3-4a88-bb50-58c8baaa0800.png)

 I don't know how these browser plug-ins work , but the name looks like the Chorm API. Can Firefox be used safely? 

 The problem happened here   `chrome.tabs.detectLanguage(sender.tab.id, result => sendResponse(result))
`

**Comment by kesc11** [comment]
Open the web page and wait a few seconds. This error will appear, but it will not affect the translation of the web page ， I don't know if it has anything to do with this mistake 

![009-16 185443](https://user-images.githubusercontent.com/51351113/190623712-a9c1abfb-5c11-4b2d-a3c9-9c4a6d121a66.png)

`Content Security Policy: The page settings prevent reading a resource located in inline ("script src"). moz-extension:113:32`

`Content Security Policy: The page settings prevent reading a resource located in inline ("script src"). moz-extension:113:176`

`Cross source request blocked: Same source policy prohibits reading at https://github.githubassets.com/assets/optimizely-e8e95f3b95e6.js Remote resources for. (Reason: CORS request failed). Status code: (null).`

**Comment by FilipePS** [comment]
While originally you would access Firefox's webextension api through the `browser` global property, Firefox accepts using `chrome` as well, which is a polyfill to facilitate the extension's compatibility with chrome.

The error `can't access property "id", sender.tab is undefined` only happens when you try to inspect the extension itself. It doesn't affect the extension in that case, I've already hidden this error message.

And the other error messages don't seem to come from my extension.

**Comment by kesc11** [comment]
Oh, I see
