### ISSUE TITLE
translate.google.cn is broken

### ISSUE THREAD

**Issue by atdfgdfbdftdrfdsf** [FilipePS/Traduzir-paginas-web#489]
Seems Chinese use translate.google.cn,but it is broken.Please turn to .com.

**Comment by Azimiao** [comment]
+1

**Comment by FilipePS** [comment]
It's been a long time since the extension doesn't use ".cn" domains to translate.
The only current option that still uses the ".cn" domain is the "Open in Google Translate" option. And I checked here and everything is working.

To translate sites the extension connects to the `translate.googleapis.com` domain. Perhaps the great Chinese Firewall has blocked this domain again. I recommend trying to use a VPN.

**Comment by HaoGe412** [comment]
可以改为translate.google.cn嘛 translate.googleapis.com 无法访问
