### ISSUE TITLE
Problem with Deepl for translate text

### ISSUE THREAD

**Issue by simonbcn** [FilipePS/Traduzir-paginas-web#568]
```
Firefox 108.0.1
Manjaro Linux
TWP 9.6.1
```
When I use Deepl to translate selected text and click on the icon, it opens the translation in a new window on the Deepl website, in addition to the addon popup window.

**Comment by Ulimn** [comment]
Does it fill the text for you on deepl.com? For me (macOS 13.3.1, Firefox 111.0.1) it just opens deepl.com without any input.

**Comment by FilipePS** [comment]
Translation with DeepL has been fixed in these commits:
https://github.com/FilipePS/Traduzir-paginas-web/commit/70be837b915c8a666ab9e85c2996a3b9830ebe16
https://github.com/FilipePS/Traduzir-paginas-web/commit/3312e5b36e5ce94f9c27acc0bfccee7b98122f11

Wait for the release of the next version. If you want, you can test the beta version: https://github.com/FilipePS/Traduzir-paginas-web/releases/tag/v9.7-beta-1
