### ISSUE TITLE
Is there a way to translate reader view?

### ISSUE THREAD

**Issue by axel9546** [FilipePS/Traduzir-paginas-web#586]
Hi there! When I use this extension https://webextension.org/listing/chrome-reader-view.html on firefox, there is no way to translate the page.
How could be possible to translate?

**Comment by FilipePS** [comment]
Sites starting with `moz-extension://` are built in extensions. My extension cannot access them and therefore cannot translate them.

I recommend you use an alternative extension like this one:
https://addons.mozilla.org/firefox/addon/tranquility-1/

**Comment by axel9546** [comment]
> Sites starting with `moz-extension://` are built in extensions. My extension cannot access them and therefore cannot translate them.
> 
> I recommend you use an alternative extension like this one: https://addons.mozilla.org/firefox/addon/tranquility-1/

Thanks so much!
But I will keep and stay with your. Really better! I hope that there could be a translation feature in the future

**Comment by FilipePS** [comment]
> > Sites starting with `moz-extension://` are built in extensions. My extension cannot access them and therefore cannot translate them.
> > I recommend you use an alternative extension like this one: https://addons.mozilla.org/firefox/addon/tranquility-1/
> 
> Thanks so much! But I will keep and stay with your. Really better! I hope that there could be a translation feature in the future

The alternative extension I mentioned earlier is `Tranquility Reader`, it is an alternative to `Reader View`, not a translation extension.
It will probably never translate when using the `Reader View` extension because the site is displayed on an internal page that other extensions do not have access to.
The `Tranquility Reader` extension works within the original website itself, so my extension can translate.
I know that `Tranquility Reader` is simple and offers few features, if you want more features you can try looking for other extensions for reading mode that are possible to translate by my extension.
