### ISSUE TITLE
The icon is not blue anymore when page is translated

### ISSUE THREAD

**Issue by mooms06** [FilipePS/Traduzir-paginas-web#653]
See the gif:

![Animation2](https://github.com/FilipePS/Traduzir-paginas-web/assets/25405517/c2c2efcf-862b-4044-a81a-37c335631d43)

Using Firefox 113.0.1 64 bits on Windows 10.

**Comment by FilipePS** [comment]
1. Open the extension's configuration page.
2. Click on the **Style** tab.
3. Make sure that the `Make the pop-up icon blue when the site is translated` option is enabled.

**Comment by mooms06** [comment]
It is enabled.

![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/25405517/b2283627-f354-4e8f-bb1b-9c55174cc129)

**Comment by FilipePS** [comment]
What theme are you using for Firefox?

**Comment by mooms06** [comment]
https://addons.mozilla.org/firefox/addon/matte-black-theme/

It worked fine previously, not sure if caused by a Firefox update or else.

**Comment by mooms06** [comment]
Update: I've tried with an old version of Firefox (109) and the icon is still not blue with the latest version of TWP.
However, with TWP version 9.6.1, the icon is blue, so the issue appears to be with TWP 9.7.x. Same behavior with Firefox 113.0.1.

**Comment by FilipePS** [comment]
The `Make the pop-up icon blue when the site is translated` option is kind of misleading in what it actually does.
Her goal has always been to make the extension's icon the same color as other Firefox icons. For example, add a site to favorites, the little star will change color, TWP tries to keep the same color.
The **Matte Black (White)** theme sets the `theme.colors.icons_attention` color to **white [rgb(255, 255, 255)]** and that's why the extension icon is turning white.
It's not a bug, the problem is actually in previous versions that didn't read the `theme.colors.icons_attention` property.

**Comment by mooms06** [comment]
I understand, but I prefer the blue icon though, because it's more obvious, so it would be a good idea to have the option to override the `theme.colors.icons_attention` property

**Comment by mooms06** [comment]
closed by error

**Comment by FilipePS** [comment]
I'm sorry but the icon color will continue to be the theme's preference.
If you think the theme is using the wrong color, simply edit the theme.
