### ISSUE TITLE
Why aren't interfaces, such as the comment section on this website, capable of being translated?

### ISSUE THREAD

**Issue by yangchen158158** [FilipePS/Traduzir-paginas-web#654]
https://www.foxnews.com/tech/flashback-stephen-hawking-warned-ai-end-human-race-years-leading-death

https://www.yahoo.com/news/belarus-president-putin-ally-alexander-020028172.html

Why can't interfaces like this website's comment section be translated?
Scroll down to the bottom, and you will be able to see the comments section. However, these cannot be translated.

**Comment by yangchen158158** [comment]
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/62718910/ffc6f2ee-4123-4439-a1a4-795b9adeafcb)

**Comment by FilipePS** [comment]
The comments section of these sites uses **Spot.IM** and the comments are contained in a `<script>` tag.
`<script>` tags are never translated by **TWP** as they normally just contain script rather than HTML markup to be translated.
In the last commit I added support for translating `<scripts>` tags as it is identified if it is a **Spot.IM** comment session.
