### ISSUE TITLE
I keep on having to activate it.  Why can't it just automatically translate non-English websites?  

### ISSUE THREAD

**Issue by github2u** [FilipePS/Traduzir-paginas-web#750]
How difficult is it to just be on by default?  I have clicked it to translate so many times today.  Shouldn't this be the default nature of this extension/add-on?

**Comment by FilipePS** [comment]
All sites being translated after installation without you configuring it is not desirable because some sites may break when translated, etc...

You can also set sites in certain languages to always be translated, see:
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/ea2371df-9b37-49f1-85cb-ecf984331588)
Note that sometimes the extension may wrongly detect the website's language, in which case you will have to force that specific website to be translated like this:
![image](https://github.com/FilipePS/Traduzir-paginas-web/assets/54990796/2012536a-4d4f-4fd7-9c68-1f3eb2b085ef)

**Comment by FilipePS** [comment]
> Any way to do this one firefox mobile? The mobile banner doesn't seem to have this option.

Due to limitations in language detection in Firefox Android, there is no option to do this in the Android version of the extension yet.

**Comment by FilipePS** [comment]
I just made a commit with a new popup mobile interface for Android.
In the next version of the extension, the `Always translate from [...]` option will be available on Android.
https://github.com/FilipePS/Traduzir-paginas-web/commit/9e41df4c724db6a4b6a71469e54523082f00600b

And I recommend using the `TWP - Translate For Mobile` extension on Android/IOS. There are installation instructions in the readme file.
https://github.com/FilipePS/Traduzir-paginas-web/blob/master/readme.md

**Comment by github2u** [comment]
I can't stand phones.  I only work with large monitors.
________________________________
