### ISSUE TITLE
BUG: Since v10.0 on Android the popup appear for 3-5 seconds on each page I load,

### ISSUE THREAD

**Issue by mikhoul** [FilipePS/Traduzir-paginas-web#779]
Since v10.0 on Android the popup appear for 3-5 seconds **on each page** I load,

![Screenshot_20240221-120717_Kiwi Browser](https://github.com/FilipePS/Traduzir-paginas-web/assets/5678673/09b63ee5-efdb-417a-8da4-afc8440f77d1)

@FilipePS  I updated the screenshot to show that when the pop-up is displayed over a web page with a white background you can see the CSS code in transparency, when the popup disappear the CSS also disappear.

It's really annoying, and with v10 the popup is lot bigger, to much IMO.

Regards ✌️

**Comment by FilipePS** [comment]
What is your device?
On a cell phone it looks fine to me.

And the popup should disappear within 6 seconds after the last interaction with it. What is sufficient time.
It's strange that it's disappearing so quickly on your device, maybe it's the low performance of your device.

**Comment by wuxyhc** [comment]
The same issue, a pop-up window will appear on each page。Android 8.1.0 ，Kiwi Browser

**Comment by mikhoul** [comment]
I use Kiwi browser.

**Comment by faramonius** [comment]
Unfortunately, version 10.0.0.1 does not solve this problem. Kiwi still shows a pop-up window like on the screenshot on every page loaded, after a few seconds it disappears. Tap with three fingers brings up the same window. Compared to version 10.0.0.0.0 the window just got a bit narrower. But I would like to return to the appearance of the control as in version 9.9.0.3 — it is much more convenient.
![IMG_20240222_121250](https://github.com/FilipePS/Traduzir-paginas-web/assets/80339829/890daf82-ceee-4930-b686-29c61332e9b7)

**Comment by FilipePS** [comment]
Do you usually keep translating/restoring the same website so that it is more convenient for the popup to always remain fixed on the screen?

**Comment by faramonius** [comment]
> Do you usually keep translating/restoring the same website so that it is more convenient for the popup to always remain fixed on the screen?

No, I usually call for an interpreter for a few minutes many times a day. I translate short pieces of text, I translate pages with answers on forums, on reddit, it is convenient for me when I can call and hide the translator quickly and arbitrarily. That's why I don't like the constantly appearing window below the omnibox.

**Comment by faramonius** [comment]
@FilipePS 
> Experimental Option: Add padding at the beginning or end of the page

If by experimental "add padding" you meant control as in 9.9.0.3, it doesn't work. Regardless of the switch position, the control looks new, as in the version starting with 10.0.0.1.

I don't want to create a new issue for such a small thing, but it's good to finalize it. A narrow control bar (or pad) at the bottom (or top, if someone uses the omnibox at the bottom) is really much more convenient. Because it is shown until the user hides it himself by clicking on the cross button. Because it looks more natural and ergonomic. Please don't leave this feature in a state of unfinished.

**Comment by FilipePS** [comment]
> @FilipePS
> 
> > Experimental Option: Add padding at the beginning or end of the page
> 
> If by experimental "add padding" you meant control as in 9.9.0.3, it doesn't work. Regardless of the switch position, the control looks new, as in the version starting with 10.0.0.1.
> 
> I don't want to create a new issue for such a small thing, but it's good to finalize it. A narrow control bar (or pad) at the bottom (or top, if someone uses the omnibox at the bottom) is really much more convenient. Because it is shown until the user hides it himself by clicking on the cross button. Because it looks more natural and ergonomic. Please don't leave this feature in a state of unfinished.

There was never any option similar to `Add padding at the beginning or end of the page` in the extension.

Have you tested the `Change Position` option in the gear options in the popup?

What that padding option does is try to add spacing at the beginning or end of the page (depending on where the popup is) in order to prevent the popup from overlapping any text.
For you to see this work you need to be at the beginning or end of the page (depending on the position of the popup). The padding at the end doesn't work so well, I recommend leaving it at the top to test the padding.

It may be necessary to reload the page.

**Comment by faramonius** [comment]
@FilipePS 
> Have you tested the Change Position option in the gear options in the popup?

Yeah, it's working normal now. The window pops up only by "three fingers" gesture, if i want. The position changes correctly. The empty space at the top is added, if that option is enabled.
It's just a pity that the window now hides _automatically_ after 7 sec. Manual control was more convenient after all old versions. :)

**Comment by FilipePS** [comment]
> @FilipePS 
> > Have you tested the Change Position option in the gear options in the popup?
> 
> Yeah, it's working normal now. The window pops up only by "three fingers" gesture, if i want. The position changes correctly. The empty space at the top is added, if that option is enabled.
> It's just a pity that the window now hides _automatically_ after 7 sec. Manual control was more convenient after all old versions. :)
> But, what’s done is done.
> 
> Thank you for the answer.

If you active the **Keep on screen** option, the popup will not be hidden after a few seconds.
