### ISSUE TITLE
 how to install addon in tor browser?

### ISSUE THREAD

**Issue by mycal123** [FilipePS/Traduzir-paginas-web#82]
↓ any work around

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

_Originally posted by @haiwx in https://github.com/FilipePS/Traduzir-paginas-web/issues/67#issuecomment-725933406_

**Comment by FilipePS** [comment]
I don't know if the tor browser supports extensions, but even if it does, I don't recommend installing this extension on it. Because the page content will be sent to Google / Yandex servers, which may compromise your privacy when using Tor.

**Comment by mycal123** [comment]
i know but that should be my choice, i can't access  science stuff with normal browser which exist on tor network. i don't care much for some cases in i have no choice. i will to leave my privacy on certain vpn. 

"you just tell me how could i intall it on tor browser."

 the new update is mess and chaos And old one is crashing and insecure.

**Comment by FilipePS** [comment]
Tor is based on Firefox, and [addons.mozilla.org](https://addons.mozilla.org) extensions can be installed directly.
Then you install the extension on the tor exactly as it installs in Firefox.

A doubt. Do you find the native chrome translator confused too?
Because the difference between the chrome translator interface and my extension is simply that my extension has 2 more buttons to translate into other languages.

And you can go back to using the old interface if you want.
